### ISSUE TITLE
Add some Retro Custom XMB to collaborate with WIKISTOR3

### ISSUE THREAD

**Issue by gboquizo** [TheWizWikii/WIKISTORE#1]
Te dejo esto por [aquí ](https://mega.nz/folder/s0wxGDwZ#pzCDygTNcAWpthq-d5h0TQ)por si te pueden resultar interesantes para la tienda. 

Son algunos retro con Custom XMB que he estado preparando hace tiempo, y no sé cómo hacértelos llegar, dejé mensaje en Twitter, pero tendrás miles y no habrás podido ver. 

Uso tu tienda desde sus primeras versiones, de hecho he aprendido todo lo que sé gracias a ti y a Nano, sois de lo mejor. 

Si te gustan y los ves convenientes, considéralos todo tuyos para poder añadir a la store, estos y los que pueda personalmente ir creando.

Muchas gracias por todo el currazo, todo lo que enseñas y por los aportes diarios, de un antiguo seguidor del canal de CYB3R.

**Comment by TheWizWikii** [comment]
Muchas gracias desde luego los usare a tu nombre!! No se cuando tendre tiempo pero bueno no los borres que cuando pueda los descargo! Saludos jefe
