### ISSUE TITLE
Problema con las carpetas

### ISSUE THREAD

**Issue by nike34** [TheWizWikii/WIKISTORE#109]
Hoy instale la wikistore y no se ven los demos de usa, los juegos completos de eur y los juegos de japon en la psx, no se si sera un bug o esta asi, lo demas perfecto.

**Comment by faissalbatir** [comment]
ya yo iba a decir eso probe a restablecer mi ps3 y poner la actualizacion oficial y luego instalar todo lo pirata y nada solucionaste bro responde rapido.
