### ISSUE TITLE
Petición juegos ps3

### ISSUE THREAD

**Issue by Angelonc14** [TheWizWikii/WIKISTORE#3]
Podrías subir a la store el Fallout 3 y el Fallout New Vegas con todos los dlcs? Para ps3 porfa y el RED DEAD REDEMPTION CON EL DLC DE ZOMBIES

**Comment by TheWizWikii** [comment]
peticiones solo aqui discord.gg/YWPZxqa

**Comment by johankevin1021** [comment]
Zumba juego de baile con el playmove si se puede cracks de igual dos muchas gracias por todo
