### ISSUE TITLE
Budokai 4 en PS3

### ISSUE THREAD

**Issue by Boss027** [TheWizWikii/WIKISTORE#9]
Hola,

Tengo cfw 4.86 rebug
Webman, multiman y rebugtoolbox a la última versión y funcionando todo correcto.
Instalo bien el juego, pero al lanzarlo la consola se queda en negro colgada.
He bajado otra ISO de internet, la monto bien con webman, pero al lanzarla me pasa el mismo error.
webman tiene activado el emulador cobra correctamente.

Alguna idea de porque no funciona? es el pkg o es mi consola?

Gracias,

**Comment by TheWizWikii** [comment]
Lo probaré

**Comment by Boss027** [comment]
Despues de mucha ayuda en los foros de discord, descubrimos que al eliminar el senenabler se solucionó.
Gracias

Enviado desde mi iPad

El 11 may 2020, a las 23:39, MaNu <notifications@github.com> escribió:

﻿

Lo probaré
